version: '3.5'

services:
  app:
    image: Xarlust/laravelwebdocker.php
    restart: unless-stopped
    volumes:
      - storage:/var/www/storage
      - public_storage:/var/www/storage/app/public
    env_file:
      - ./.env
   
  nginx:
    image: Xarlust/laravelwebdocker.nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - public_storage:/var/www/public/storage
    depends_on:
      - app

#  redis:
#    image: redis:rc-alpine
#    restart: unless-stopped

volumes:
  storage:
  public_storage:
