version: '3.5'

services:
  app:
    image: xarlust/laravelwebdocker.php
    build:
      context: .
      dockerfile: build/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    

  nginx:
    image: xarlust/laravelwebdocker.nginx
    build:
      context: .
      dockerfile: build/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
    depends_on:
      - app

#  redis:
#    image: redis:rc-alpine
#    restart: unless-stopped

volumes:
  storage:
  public_storage:
